// import { StateGraph, StateSchema, type GraphNode, START, END } from "@langchain/langgraph";
// import z from "zod";
// import { ModelProvider } from "./model.ai.js";
// import { createAgent, HumanMessage, providerStrategy } from "langchain";


// const state = new StateSchema({
//     problem: z.string().default(""),
//     solution_1: z.string().default(""),
//     solution_2: z.string().default(""),
//     judge: z.object({
//         solution_1_score: z.number().default(0),
//         solution_2_score: z.number().default(0),
//         solution_1_reasoning: z.string().default(""),
//         solution_2_reasoning: z.string().default("")
//     })
// })

// const solutionNode: GraphNode<typeof state> = async (state) => {

//     const [mistralResponse, cohoreaiResponse] = await Promise.all([
//         ModelProvider.mistral.invoke(state.problem),
//         ModelProvider.cohere.invoke(state.problem)
//     ])

//     return {
//         solution_1: mistralResponse.text,
//         solution_2: cohoreaiResponse.text,
//     }
// }

// const judgeNode: GraphNode<typeof state> = async (state) => {

//     const { problem, solution_1, solution_2 } = state

//     const judge = createAgent({
//         model: ModelProvider.gemini,
//         responseFormat: providerStrategy(z.object({
//             solution_1_score: z.number().min(0).max(10),
//             solution_2_score: z.number().min(0).max(10),
//             solution_1_reasoning: z.string(),
//             solution_2_reasoning: z.string(),
//         })),
//         systemPrompt: `You are a judge task with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the score`
//     })

//     const judgeResponse = await judge.invoke({
//         messages: [
//             new HumanMessage(`
//                 Problem: ${problem}
//                 Solution 1: ${solution_1}
//                 Solution 2: ${solution_2}
//                 Please evaluate the solutions and provide scores and reasoning.
//                 `)
//         ]
//     })

//     const {
//         solution_1_score,
//         solution_2_score,
//         solution_1_reasoning,
//         solution_2_reasoning
//     } = judgeResponse.structuredResponse

//     return {
//         judge: {
//             solution_1_score,
//             solution_2_score,
//             solution_1_reasoning,
//             solution_2_reasoning,
//         }
//     }
// }

// const graph = new StateGraph(state)
//     .addNode("solution", solutionNode)
//     .addNode("judge", judgeNode)
//     .addEdge(START, "solution")
//     .addEdge("solution", "judge")
//     .addEdge("judge", END)
//     .compile()

// export default async function (problem: string) {

//     const result = await graph.invoke({
//         problem: problem
//     })
//     return result

// }

import { StateGraph, Annotation, START, END } from "@langchain/langgraph"; // Newer versions use Annotation
import z from "zod";
import { ModelProvider } from "./model.ai.js";
import { HumanMessage } from "@langchain/core/messages";

// 1. Define the State properly using Annotation (Standard for latest LangGraph)
const StateAnnotation = Annotation.Root({
    problem: Annotation<string>(),
    solution_1: Annotation<string>(),
    solution_2: Annotation<string>(),
    // 'judge' yahan as a state attribute use ho raha hai
    judge: Annotation<{
        solution_1_score: number;
        solution_2_score: number;
        solution_1_reasoning: string;
        solution_2_reasoning: string;
    }>(),
});

// 2. Solution Node
const solutionNode = async (state: typeof StateAnnotation.State) => {
    // parallel processing for speed
    const [mistralResponse, cohereResponse] = await Promise.all([
        ModelProvider.mistral.invoke(state.problem),
        ModelProvider.cohere.invoke(state.problem)
    ]);

    return {
        solution_1: mistralResponse.content as string, // LangChain returns content
        solution_2: cohereResponse.content as string,
    };
};

// 3. Judge Node (Renamed the Node to avoid conflict)
const judgeNode = async (state: typeof StateAnnotation.State) => {
    const { problem, solution_1, solution_2 } = state;

    // Industry Standard: Using .withStructuredOutput for cleaner parsing
    const structuredJudge = ModelProvider.gemini.withStructuredOutput(z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
    }));

    const systemPrompt = `You are a judge tasked with evaluating two solutions.
    Problem: ${problem}
    Solution 1: ${solution_1}
    Solution 2: ${solution_2}
    Please provide scores (0-10) and reasoning.`;

    const response = await structuredJudge.invoke([
        new HumanMessage(systemPrompt)
    ]);

    return {
        judge: response // 'judge' is the key in our state
    };
};

// 4. Build the Graph
const workflow = new StateGraph(StateAnnotation)
    .addNode("solution_providers", solutionNode) // Node name is different from state keys
    .addNode("evaluator", judgeNode)            // Node name changed to 'evaluator'
    .addEdge(START, "solution_providers")
    .addEdge("solution_providers", "evaluator")
    .addEdge("evaluator", END);

export const graph = workflow.compile();

export default async function runBattle(problem: string) {
    const result = await graph.invoke({ problem });
    return result;
}

